import type { Metadata } from "next";
import { Bangers } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { Analytics } from '@vercel/analytics/next';

const bangers = Bangers({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bangers",
});

export const metadata: Metadata = {
  title: "Easy-Learn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bangers.variable} antialiased`}>
        {children}
        <ToastContainer position="top-center" autoClose={2000} />
        <Analytics />
      </body>
    </html>
  );
}
